### ISSUE TITLE
G3 codes

### ISSUE THREAD

**Issue by pdionisis** [ca0ss/ToolOPT6-Calculator#1]
Hello
I have an LG oled55G36LA.
Dvr is disabled.
My menu is exactly the same as your programm except that "ECO default backlight" is "Default  backlight" at me.
Tried to put my settings at your programm to see if the code matches but it does not (i guess because of the more options at some parameters)

Also at EDID_TYPE I have default the option "TRUEHD+DTS" which is unavailable at your software but it is unlocked and chose the simple TRUEHD mode.

The code I see when i put truehd is 1645270539
I want to enable dvr
![original with truehd](https://github.com/ca0ss/ToolOPT6-Calculator/assets/35379434/2dc67834-a7ee-4606-a814-8468b081cc51)

With default backlight = 50  ----> 1645270283
With default backlight = 45  ----> 1645270027
the range is 25-100 with increments of 5 (25-30-35.....100)

The wifi has 11 options instead of the 7 of your programm (extra: single_22Y, M_single_22Y, dual_23Y, single_23Y)

EDID  has 4 options at me instead 3 yours (TrueHD+dts, ac3, ac3+dts, trueHD)

The other options are greyd and can not check the possible values

Any help?
I can for example change the Default  backlight(it is unlocked) and write the different values of the code

I only want to enable dvr

Thank you

**Comment by ca0ss** [comment]
The bin of your original code is "1100010000100001101011000001011"

You have 4 parameter to look at: 
ISF = 1
SET ID = 1
SUPPORT ATV DVR = 0
DVR Ready = 0
AUDIO LINE OUT = 0

the only pattern that match on your binary value is from 13° to 17° value.
To enable DVR option you should edit in this way:
1100010000100111101011000001011
That became
**1645467147**

If you want to implement your TV on my app, please write me on telegram at @Ca0ss93 and send me some photo of your tool opt6 menu. I need that you try to change every option and send me a photo of the menu :)

**Comment by ca0ss** [comment]
Please send me feedback so i can close this issue :)

**Comment by pdionisis** [comment]
It worked !!!
Thank you
