### ISSUE TITLE
How to input the finished code?

### ISSUE THREAD

**Issue by tsamo** [ca0ss/ToolOPT6-Calculator#2]
Using a LG C2 42'' TV. Menu is identical except an extra option under the previous ones, called Markone WiFi Single. The calculator seems to work just fine though.

The main issue, is this: maybe I missed it, but I cannot find a way to input the finished code on the tv. 
I tried just pressing ok on it, clicking right, connecting an external keyboard and typing it, going to the InStart menu and trying there just in case, but I am currently baffled.

Any ideas?

**Comment by pdionisis** [comment]
I can not help with the typing .
I would say though that if the menu is not identical (also you need the same count of options at every parameter) I would double check the code from the programm and try to find myself the algorithm just to be sure.

Does the ezadjust let you change other parameters or it does not let you change anything?

**Comment by tsamo** [comment]
Trying on other options on the menu, it lets me change some of them(number keyboard appears) but not others.
Changing the options on Opt6 and crossreferencing the code with the tool seems to work as intended otherwise.

![20231128_191353](https://github.com/ca0ss/ToolOPT6-Calculator/assets/37329391/ffb5dd87-1e5e-4ef9-8e5f-90d26ca32dde)

**Comment by ca0ss** [comment]
Normally you should press "OK" on the number, maybe LG figured out that we understand the "algorithm" and make the number read only. If you have jailbreack on the tv, we can try a thing..

**Comment by ca0ss** [comment]
There is a "oml" file that manage if the input is editable or not. You can temporarily mount a modded file to unlock the input field amd enable dvr feature. Please dm me on Telegram: t.me/Ca0ss93

**Comment by ca0ss** [comment]
I will close the issue, my app can calculate the code but for locked menu you need jailbreak of the tv and manipulation of some qml file.
