### ISSUE TITLE
On OLED XXC26LB I cannot modify the ToolOPT6 Field

### ISSUE THREAD

**Issue by ebr9999** [ca0ss/ToolOPT6-Calculator#3]
The calculator works fine (I have verified that based on the values I read the ToolOPT6 field is the one computed by the calculator), 
but the field in the SM item cannot be modified.

**Comment by ebr9999** [comment]
Hi, 

Can you please clarify what I should do to receive help on unlocking that field?

Enrico

**Comment by ca0ss** [comment]
For unlock that field you need to have the root on your tv; you can achieve this with the jailbreak.
With the root you can tamper some qml file that will unlock that field.

If you want, i can help you; please send me a message on telegram, my username there is Ca0ss93. You can use this link to direct https://t.me/Ca0ss93

**Comment by ca0ss** [comment]
I will close the issue, there is my direct contact for this issue
