### ISSUE TITLE
Help for LG OLED48CX3LB

### ISSUE THREAD

**Issue by colemar** [ca0ss/ToolOPT6-Calculator#4]
LG OLED48CX3LB
![image](https://github.com/user-attachments/assets/5c427d01-a620-40fb-b6f5-3046131e02e3)

I clicked on [Help], answered the questions and the item list became identical to what I see on my TV.
Then I put in the field [Code] the current code seen on my TV, which is 1649924873, and clicked on [Reverse].
Here is the result:

![image](https://github.com/user-attachments/assets/2a5fb2ac-a04b-4d5f-ba4b-4c26c87639c7)

Can you help me?
@ca0ss ping

**Comment by colemar** [comment]
@ca0ss I would like to enable DVR functions in Italy.

**Comment by ca0ss** [comment]
Ciao! Da quello che leggo e vedo nella tua foto, hai già il PVR attivo :)

Se hai telegram, ti invito a scrivermi un messaggio privato, ti mando qualche video dove ti spiego come fare :)

**Comment by ca0ss** [comment]
https://www.avmagazine.it/forum/127-display-e-tv-4k-e-8k/326568-attivazione-timeshift-e-registrazione-su-oled-lg-quot-stranieri-quot

Ti ho mandato una guida più o meno dettagliata via mail, per completezza ti mando una guida non mia con questo link.
Non chiudo questa issue in quanto devo capire cosa ha generato l'errore, però se segui quello che ti ho scritto avrai ciò che desideri :)

**Comment by ca0ss** [comment]
come scritto via mail, ti sarei grato se tu mi inviassi delle foto in cui mostri tutte le voci presenti in EDID Type con relativo codice, in quanto la tua tv è un modello che ha un menù differente dagli altri e vorrei aggiungere il supporto :)

**Comment by colemar** [comment]
Certo, oggi stesso in serata provvedo.

**Comment by colemar** [comment]
Ecco qua.
Poi ho fatto scorrere anche gli altri 3 valori selezionabili.
[OLED48CX3LB.zip](https://github.com/user-attachments/files/17560302/OLED48CX3LB.zip)

**Comment by ca0ss** [comment]
Ti ringrazio per le foto, mi sono veramente utili :)
Durante i miei test con la serie UN7300 non avevo mai provato a cambiare i tipi di audio EQ.
devo capire se la tua tv ha una codifica differente o io ho sbagliato a codificare il 7300.  A breve rilascerò un aggiornamento :)

**Comment by ca0ss** [comment]
Fixed on release [Stable v1.4](https://github.com/ca0ss/ToolOPT6-Calculator/releases/tag/Stable1.4)
