### ISSUE TITLE
Different options in toolOPT6_Energy/Country menu

### ISSUE THREAD

**Issue by fabiosci** [ca0ss/ToolOPT6-Calculator#5]
Hi,
I own a LG OLED55B42LA with webOS 24. I noticed that:

1. The toolOPT6_Energy/Country menu does not have the "Support ATV/AV DVR" option
2. I see the "Support Calman SW" where I expected to see the Support ATV/AV DVR

Here is a screenshot of my menu:
![service menu](https://github.com/user-attachments/assets/1cff01ca-0861-4265-9c8c-562d2df48da3)

Using the Help button, the calculator selected the G36LA TV series.
Moreover, I put my code in the calculator and used the Reverse function. All the options were the same between calculator and TV.

So my questions:
- considering the different menu, is it safe to use the Code calculated with the calculator in this situation? I'm worried about bricking the TV
- any idea to explain why the Support ATV/AV DVR option is no longer present?
- if I enable the DVR Ready option would I be able to record tv programs on a USB stick or disk?

thanks a lot,
fabio

**Comment by ca0ss** [comment]
Hello! The voice missing on your tv, probably is referred to Analog TV DVR. I guess that on newer tv, LG remove the ATV decoder for the switch off and the fact that they will never use it again.

The solution should be enable just DVR Ready, but there is a catch:

You have a new tv model and you cannot edit the number on the tv, and you cannot make the jailbreak to edit it anyway using current public jailbreak available.

Please consider to contact me on Telegram, maybe there is a solution that we can use.

Se sei italiano ci capiamo meglio ;)

**Comment by fabiosci** [comment]
Ciao, sono italiano e ci capiamo meglio nella nostra lingua. Grazie mille
per la veloce risposta e la disponibilità. Come ti posso contattare su
telegram?

Il Sab 26 Ott 2024, 17:39 ca0ss ***@***.***> ha scritto:

**Comment by ca0ss** [comment]
Cerca su telegram Ca0ss93, puoi anche cliccare sulla parola Telegram del messaggio precedente :)

**Comment by fabiosci** [comment]
Ho risposto direttamente dalla mail e il link non c'era ;)

Il Sab 26 Ott 2024, 18:52 ca0ss ***@***.***> ha scritto:

**Comment by ca0ss** [comment]
Added support to OLED55B42LA series on the new 1.3 release,  #grazie :)
