### ISSUE TITLE
Longer than expected ToolOpt6 code on 55QNED816RE (Italy Base)-10 digits vs 9

### ISSUE THREAD

**Issue by CAM-biteme** [ca0ss/ToolOPT6-Calculator#6]
Ciao,
ToolOPT6-Calculator worked like a charm (thank you!) on a tiny 28TN515S-PZ.
On the 55QNED816RE however, the Reverse option does recognize the Energy/Country code as a valid one (1395705355).
I am assuming the TV set may have a new option that you have not decoded yet (in fact, If I  compare the 28inches vs the 55, the bigger one has an Extra WiFi option called "WiFi Assy type").

Anychance you think this could be  sorted out? Happy to share any relevant detail of my Tv set if this can help the community in using a simple option like DVR instead of buying an additional set-top box to perform the same task..
![Screenshot 2024-10-27 alle 10 32 23](https://github.com/user-attachments/assets/2ad9c16c-f982-42a7-ab9e-f8b68189b2e5)

Grazie mille!
![Screenshot 2024-10-27 alle 10 09 24](https://github.com/user-attachments/assets/5ca862ec-0211-41a0-a485-219e396688cc)

**Comment by ca0ss** [comment]
Ciao!
Next time try the "Help" button :)
Select "G36LA" on TV series, then use "Reverse" button
![Screenshot 2024-10-28 120123](https://github.com/user-attachments/assets/b07b6d80-6e1b-4ffe-9462-b48e34515ca0)
Remember that if you enable PVR on a country where PVR shouldn't be used, you probably need to change country in settings

**Comment by ca0ss** [comment]
https://github.com/ca0ss/ToolOPT6-Calculator/compare/Stable1.2...Stable1.3
